Weather APP - JS branch Feature v1
brugobi/Weather-App-JS pull request #3
Opened 2020-12-14 21:40 UTC by brugobi

## Weather app

Here is the weather app project building with JS and API

### Features

- [X] Get weather informations by getting the user location if the user accept it;

- [X] Get weather informations by typing the city's name;

- [X] Autocomplete functionality for cities names;

- [X] Temperature available in Celsius and Fahrenheit by clicking on the temperature number;

### Thanks for reviewing my code

2020-12-14 22:43 UTC, mosaaleb requested changes
#### Changes required

Excellent job @brugobi :clap:. You have done an amazing job on this project. Adding the autocomplete feature is very powerful. Geolocation also is very handy. Yet there are other requirements that need to be handled before moving on.

- [ ] It changes its appearance based on the received data:
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png)

- [ ] **[OPTIONAL]** t has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png)

Please handle these requirements and submit a new code review

##### Muhammad Ebeid

2020-12-14 22:43 UTC, mosaaleb commented on src/index.html
> +                <div class="weather-icon"><img src="icons/unknown.png" alt=""></div>
- [ ] There is an console error coming from the image source. Let's fix the used image path
![Screenshot from 2020-12-15 00-20-03](https://user-images.githubusercontent.com/4246637/102142588-56959b00-3e6b-11eb-80ec-7b3c15585fb5.png)

2020-12-14 22:43 UTC, mosaaleb commented on src/index.js
> +    console.log(err);
- [ ] No `console.log` commited to repo. It kills performance.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png)

We can replace the error handling by displaying the information in a notification box.

2020-12-14 22:43 UTC, mosaaleb commented on src/index.js
> +const displayWeather = () => {
- [ ] Since this function is a DOM-related, maybe we should move it to `dom.js`?

2021-02-08 19:02 UTC, brugobi commented
- Updated the code adding all the recommendations requested;

2021-02-08 19:18 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval. 
**Nice UI concept also. 👌**

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-02-08 20:06 UTC, merged